Repository AY2021S2-CS2103T-T11-1/tp, pull requests merged in 2021-03, with the labels that each got.

#44 Update developer guide NFRs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/yungweezy.png
  docs/team/yungweezy.md
Labels: type.Documentation

#43 Add Session class to TutorBuddy
  src/main/java/seedu/address/model/session/Duration.java
  src/main/java/seedu/address/model/session/Fee.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/model/session/Subject.java
  src/main/java/seedu/address/model/session/exceptions/SessionException.java
  src/test/java/seedu/address/model/session/DurationTest.java
  src/test/java/seedu/address/model/session/FeeTest.java
  src/test/java/seedu/address/model/session/SessionDateTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/model/session/SubjectTest.java
Labels: priority.High, type.Story

#47 Update UG to resolve hyperlink bug and also include _ for all the commands
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#50 V1.2 list of sessions
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Task

#70 Update find student UG
  docs/UserGuide.md
Labels: type.Documentation

#67 Session UI
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/commands/FindStudentCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/session/Duration.java
  src/main/java/seedu/address/model/session/Fee.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/model/session/Subject.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/java/seedu/address/ui/SessionListPanel.java
  src/main/resources/view/SessionListCard.fxml
  src/main/resources/view/SessionListPanel.fxml
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: priority.Medium

#73 Delete Session + Session Storage
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/Duration.java
  src/main/java/seedu/address/model/session/Fee.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/model/session/Subject.java
  src/main/java/seedu/address/model/session/exceptions/SessionException.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSessionCommandTest.java
  src/test/java/seedu/address/model/session/SessionDateTest.java
  src/test/java/seedu/address/model/session/SessionTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, type.Epic

#72 Update email UG and standardize to using examples instead of example
  docs/UserGuide.md
Labels: type.Documentation

#75 Add list session command
  src/main/java/seedu/address/logic/commands/ListSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListSessionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Low, type.Task

#80 Add tuition link class
  src/main/java/seedu/address/model/tuition/Tuition.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SessionListPanel.java
  src/main/java/seedu/address/ui/TuitionCard.java
  src/main/java/seedu/address/ui/TuitionListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TuitionListCard.fxml
  src/main/resources/view/TuitionListPanel.fxml
Labels: priority.Medium, type.Enhancement

#78 Add Session tests
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/test/java/seedu/address/logic/commands/AddSessionCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/testutil/SessionUtil.java
Labels: priority.Medium, type.Testing

#86 Rename window title
  src/main/resources/view/MainWindow.fxml
Labels: priority.Low, type.Bug

#85 Update UG to include monthly fee command
  docs/UserGuide.md
Labels: type.Documentation

#83 Improve code quality in v1.2
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
Labels: priority.Low

#88 Add assertions as per requirement
  build.gradle
Labels: type.Task

#92 DG update: add session implementation
  docs/DeveloperGuide.md
  docs/diagrams/junwei/AddSessionSequenceDiagram.puml
  docs/images/junwei/AddSessionSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
Labels: priority.High, type.Documentation

#93 DG update: add student implementation & update logic diagram
  docs/DeveloperGuide.md
  docs/diagrams/enhao/AddStudentActivityDiagram.puml
  docs/diagrams/enhao/DeleteStudentSequenceDiagram.puml
  docs/images/enhao/AddStudentActivityDiagram.png
  docs/images/enhao/DeleteStudentSequenceDiagram.png
Labels: type.Documentation

#101 DG update: Email Command
  docs/DeveloperGuide.md
  docs/diagrams/sam/EmailCommandActivityDiagram.puml
  docs/diagrams/sam/EmailCommandSequenceDiagram.puml
  docs/images/sam/EmailCommandActivityDiagram.png
  docs/images/sam/EmailCommandSequenceDiagram.png
Labels: priority.Medium, type.Documentation

#97 Add test cases for Tuition class
  src/test/java/seedu/address/model/tuition/TuitionTest.java
Labels: priority.Medium, type.Testing

#100 DG update: add student implementation
  docs/DeveloperGuide.md
  docs/diagrams/choonwei/ListStudentActivityDiagram.puml
  docs/diagrams/choonwei/ListStudentSequenceDiagram.puml
  docs/diagrams/choonwei/style.puml
  docs/images/choonwei/ListStudentActivityDiagram.png
  docs/images/choonwei/ListStudentSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
Labels: priority.Medium, type.Documentation

#105 Fix Email Command Bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
Labels: priority.Medium, type.Bug

#111 Fix Student/SessionBuilder bug
  src/test/java/seedu/address/logic/commands/AddSessionCommandTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, type.Bug

#112 Fix add overlapping session bug
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/Duration.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/session/DurationTest.java
Labels: priority.High, type.Bug

#116 Fix print site header for UG
  docs/_sass/minima/_base.scss
Labels: priority.Medium, type.Documentation

#118 Get monthly fee + Get 3 months fee (this month + prev 2 months) function (Only supports non-recurring session for now)
  src/main/java/seedu/address/logic/commands/GetMonthlyFeeCommand.java
  src/main/java/seedu/address/logic/commands/GetPrev3MonthFeeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GetMonthlyFeeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/fee/Month.java
  src/main/java/seedu/address/model/fee/Year.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/model/fee/MonthTest.java
  src/test/java/seedu/address/model/fee/YearTest.java
Labels: type.Story

#130 UG: Add command format and logo
  docs/UserGuide.md
  docs/images/TutorBuddyLogo.jpeg
Labels: type.Documentation

#131 UG Update: Quick start and UI images
  docs/UserGuide.md
  docs/images/ApplicationOverview.png
  docs/images/Ui.png
  docs/images/tutorbuddy_logo.png
Labels: priority.High, type.Documentation

#120 Add UG tips, help and clear section
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#127 Add recurring session command -UG
  docs/UserGuide.md
Labels: priority.Medium

#129 Update TutorBuddy description and changed some command description
  docs/UserGuide.md
Labels: priority.Low, type.Documentation

#125 Minor edit on UG to add purpose
  docs/UserGuide.md
Labels: type.Documentation

#106 Shion recurring session
  src/main/java/seedu/address/logic/commands/AddRecurringSessionCommand.java
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddRecurringSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/session/Interval.java
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/storage/JsonAdaptedRecurringSession.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/ui/TuitionCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/DeleteSessionCommandTest.java
  src/test/java/seedu/address/model/session/RecurringSessionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
Labels: priority.High

#135 Modified UG and added in sub headers for student and session commands.
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#119 Add UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/java/seedu/address/ui/TuitionCard.java
  src/main/java/seedu/address/ui/TuitionListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UpcomingTuitionCard.java
  src/main/java/seedu/address/ui/UpcomingTuitionListPanel.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/tutorbuddy_icon.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SessionListCard.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/TabTheme.css
  src/main/resources/view/TuitionListCard.fxml
  src/main/resources/view/TuitionListPanel.fxml
  src/main/resources/view/UpcomingTuitionCard.fxml
  src/main/resources/view/UpcomingTuitionListPanel.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: priority.High

#137 Finalized UG Update for CS2101
  docs/UserGuide.md
  docs/images/TutorBuddyLogo.jpeg
  docs/images/command_list.png
  docs/images/helpMessage.png
Labels: priority.High, type.Documentation

#144 ensure numOfSession works by itself
  src/main/java/seedu/address/model/session/RecurringSession.java
Labels: priority.High, type.Bug

#148 Add a getFullStudentList method to logic and update upcoming tuition panel to use this list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement

#142 Calendar Feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CalendarCard.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/Calendar.css
  src/main/resources/view/CalendarCard.fxml
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium

#147 RecurringSession Method
  src/main/java/seedu/address/model/session/RecurringSession.java
Labels: type.Bug

#153 Update edit student to be workable for guardian phone, study level and relationship as well
  src/main/java/seedu/address/logic/commands/EditStudentCommand.java
  src/test/java/seedu/address/logic/parser/EditStudentCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
Labels: priority.High, type.Enhancement

#152 Is valid end output error
  src/main/java/seedu/address/logic/parser/AddRecurringSessionCommandParser.java
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/test/java/seedu/address/model/session/RecurringSessionTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/testutil/RecurringSessionBuilder.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High, severity.Medium

#145 3 Month UI that supports both single and recurring session
  bin/main/view/DarkTheme.css
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/commons/util/FeeUtil.java
  src/main/java/seedu/address/logic/commands/GetMonthlyFeeCommand.java
  src/main/java/seedu/address/logic/commands/GetPrev3MonthFeeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/fee/MonthlyFee.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MonthlyFeeCard.java
  src/main/java/seedu/address/ui/MonthlyFeeListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MonthlyFeeListCard.fxml
  src/main/resources/view/MonthlyFeeListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: priority.High, type.Story

#143 Monthly Fee for Recurring Session
  src/main/java/seedu/address/commons/util/FeeUtil.java
Labels: type.Story

#128 Include test cases for getmonthlyfee and increase coverage for add student and month
  src/main/java/seedu/address/logic/commands/GetMonthlyFeeCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GetMonthlyFeeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GetMonthlyFeeCommandParserTest.java
  src/test/java/seedu/address/model/fee/MonthTest.java
  src/test/java/seedu/address/model/session/RecurringSessionTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Testing

#146 Update UI for Reminder Section
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/java/seedu/address/ui/TuitionListPanel.java
  src/main/java/seedu/address/ui/UpcomingTuitionListPanel.java
  src/main/resources/view/SessionListCard.fxml
Labels: priority.High

#159 UI: Add End Date and UI
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SessionListCard.fxml
Labels: priority.High

#155 Add delete session from recurring session feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteRecurringSessionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteRecurringSessionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
Labels: priority.Medium, type.Enhancement
