Repository AY2021S2-CS2103T-T11-1/tp, pull requests merged in 2021-04, with the labels that each got.

#167 Remove list_session and change list_student to list
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#166 Include some sample session when a user first starts the app
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, type.Enhancement

#170 Change Ui dates to follow dd MMM YYYY format
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/java/seedu/address/ui/UpcomingTuitionCard.java
Labels: priority.Medium

#169 Help Window: Add command information
  src/main/java/seedu/address/logic/commands/AddRecurringSessionCommand.java
  src/main/java/seedu/address/ui/CommandHelper.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#168 UG: Add delete recurring session
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#150 Fix bug in checking for overlapping sessions.
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/session/RecurringSessionTest.java
Labels: priority.Medium, type.Bug

#173 UG update: Add UI screenshots with some descriptions
  docs/UserGuide.md
  docs/images/CalendarPage.png
  docs/images/HomePage.png
  docs/images/TuitionPage.png
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: priority.Medium, type.Documentation

#165 Branch improve test
  src/main/java/seedu/address/model/fee/MonthlyFee.java
  src/test/java/seedu/address/logic/commands/GetMonthlyFeeCommandTest.java
  src/test/java/seedu/address/model/fee/MonthlyFeeTest.java
  src/test/java/seedu/address/model/fee/YearTest.java
  src/test/java/seedu/address/testutil/RecurringSessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Testing

#255 Add inclusive to month and year, add space to example commands
  docs/UserGuide.md
Labels: type.Documentation

#103 Dg shion session feature
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/shion/ArchitectureSequenceDiagram.puml
  docs/diagrams/shion/DeleteSessionSequenceDiagram.puml
  docs/diagrams/shion/SessionClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/shion/ArchitectureSequenceDiagram.png
  docs/images/shion/DeleteSessionSequenceDiagram.png
  docs/images/shion/SessionClassDiagram.png
  docs/tutorials/TracingCode.md
Labels: priority.Medium, type.Documentation

#260 First Draft PPP for enhao
  docs/team/enhao25.md
Labels: type.Documentation

#253 Fix result display click copies bug
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Medium, type.Bug

#254 Update UG for fee and to not allow for session fee to be 1000000 or more
  docs/UserGuide.md
  src/main/java/seedu/address/model/session/Fee.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/session/FeeTest.java
Labels: severity.High, type.Bug

#252 Fix emails command duplicate issue
  src/main/java/seedu/address/logic/commands/EmailCommand.java
  src/test/java/seedu/address/logic/commands/EmailCommandTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.Medium, type.Bug

#263 First draft for PPP
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/enhao25.md
  docs/team/samleewy.md
Labels: type.Documentation

#268 Fix broken hyperlinks in the UG
  docs/UserGuide.md
Labels: priority.High, type.Bug, type.Documentation

#258 Add rec session/suggest end date
  src/main/java/seedu/address/logic/parser/AddRecurringSessionCommandParser.java
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/test/java/seedu/address/model/session/RecurringSessionTest.java
Labels: priority.High

#269 User guide: PED Bug Fixes
  docs/UserGuide.md
Labels: type.Documentation

#275 Shion's Draft for PPP
  docs/team/nowknowing.md
Labels: type.Documentation

#270 Update DG with use cases for fees + update student commands
  docs/DeveloperGuide.md
Labels: priority.High

#276 Choon Wei's PPP draft
  docs/team/enhao25.md
  docs/team/yungweezy.md
Labels: priority.Low, type.Documentation

#271 Resolve monthly fee bug + improve test coverage
  src/main/java/seedu/address/model/fee/MonthlyFee.java
  src/test/java/seedu/address/logic/commands/GetMonthlyFeeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/student/AddressTest.java
  src/test/java/seedu/address/model/student/EmailTest.java
  src/test/java/seedu/address/model/student/NameTest.java
  src/test/java/seedu/address/model/student/PhoneTest.java
Labels: type.Testing

#265 Change addressbook instance to tutorbuddy
  preferences.json
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: priority.Low, type.Bug

#273 Update UG based on aileen comments
  docs/UserGuide.md
Labels: type.Documentation

#277 Change command feedback based on PED feedback
  src/main/java/seedu/address/logic/commands/AddSessionCommand.java
Labels: priority.Low, type.Bug

#281 DeleteSession command and parser tests
  src/test/java/seedu/address/logic/commands/DeleteSessionCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteSessionCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Testing

#289 Fixed to yyyy
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/java/seedu/address/ui/UpcomingTuitionCard.java
Labels: type.Bug

#287 SessionDate follows 2038 problem
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/GetMonthlyFeeCommand.java
  src/main/java/seedu/address/logic/parser/GetMonthlyFeeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Year.java
  src/main/java/seedu/address/model/fee/MonthlyFee.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/ui/MonthlyFeeListPanel.java
  src/test/java/seedu/address/logic/commands/GetMonthlyFeeCommandTest.java
  src/test/java/seedu/address/logic/parser/GetMonthlyFeeCommandParserTest.java
  src/test/java/seedu/address/model/YearTest.java
  src/test/java/seedu/address/model/fee/MonthlyFeeTest.java
  src/test/java/seedu/address/model/session/SessionDateTest.java
Labels: type.Task

#291 Pull from "nus-cs2103-AY2021S2" to ensure that we have "resolved" the bugs that they have resolved
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Documentation

#278 Improve code quality of delete_rec_session
  docs/UserGuide.md
  docs/images/DeleteRecurringSession.png
  src/main/java/seedu/address/logic/commands/DeleteRecurringSessionCommand.java
  src/main/java/seedu/address/logic/parser/DeleteRecurringSessionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteRecurringSessionCommandTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: priority.Medium, type.Documentation, type.Task, type.Testing

#290 Fix reminder bug where a single session on third session does not show
  src/main/java/seedu/address/ui/UpcomingTuitionListPanel.java
Labels: priority.High, type.Bug

#292 Add tips to UG to inform user about tab switching
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#286 Fix calendar card ugly border and color on click
  src/main/resources/view/Calendar.css
  src/main/resources/view/CalendarCard.fxml
Labels: priority.Medium, type.Bug

#293 UG/ names are case-insensitive and disallow duplicate
  docs/UserGuide.md
Labels: type.Documentation

#279 DG Update: Finalise use case
  docs/DeveloperGuide.md
Labels: type.Documentation

#274 Update DG: Implementation details
  docs/DeveloperGuide.md
  docs/diagrams/enhao/AddStudentSequenceDiagram.puml
  docs/diagrams/enhao/GetMonthlyFeeSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/enhao/AddStudentSequenceDiagram.png
  docs/images/enhao/GetMonthlyFeeSequenceDiagram.png
Labels: type.Documentation

#283 Test/recurring session
  docs/team/nowknowing.md
  src/main/java/seedu/address/logic/parser/AddRecurringSessionCommandParser.java
  src/main/java/seedu/address/model/session/RecurringSession.java
  src/test/java/seedu/address/logic/commands/AddRecurringSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddRecurringSessionCommandParserTest.java
  src/test/java/seedu/address/model/session/IntervalTest.java
  src/test/java/seedu/address/model/session/RecurringSessionTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Bug, type.Testing

#299 DG: Update UI Component Class diagram + Update Links
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/ui/SessionCard.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/TuitionCard.java
  src/main/resources/view/SessionCard.fxml
  src/main/resources/view/StudentCard.fxml
  src/main/resources/view/TuitionCard.fxml
Labels: type.Documentation

#301 add year methods in DateUtil.java
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/GetMonthlyFeeCommand.java
  src/main/java/seedu/address/logic/parser/GetMonthlyFeeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/fee/MonthlyFee.java
  src/main/java/seedu/address/model/fee/Year.java
  src/main/java/seedu/address/model/session/SessionDate.java
  src/main/java/seedu/address/ui/MonthlyFeeListPanel.java
  src/test/java/seedu/address/logic/commands/GetMonthlyFeeCommandTest.java
  src/test/java/seedu/address/logic/parser/GetMonthlyFeeCommandParserTest.java
  src/test/java/seedu/address/model/YearTest.java
  src/test/java/seedu/address/model/fee/MonthlyFeeTest.java
Labels: type.Bug

#302 Update UG: Base on comments in the pdf
  docs/UserGuide.md
Labels: type.Documentation

#305 Add tests for AddSessionCommandParser
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddSessionCommandParserTest.java
Labels: type.Testing

#304 DG: Add manual testing section
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#300 Move test cases for delete recurring session
  src/main/java/seedu/address/model/student/UniqueStudentList.java
  src/test/java/seedu/address/logic/commands/DeleteRecurringSessionCommandTest.java
  src/test/java/seedu/address/model/session/RecurringSessionTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
Labels: priority.High, type.Task

#303 Update list command implementation and add delete recurring session i…
  docs/DeveloperGuide.md
  docs/diagrams/choonwei/DeleteRecurringSessionActivityDiagram.puml
  docs/diagrams/choonwei/DeleteRecurringSessionSequenceDiagram.puml
  docs/diagrams/choonwei/ListActivityDiagram.puml
  docs/diagrams/choonwei/ListSequenceDiagram.puml
  docs/diagrams/choonwei/ListStudentSequenceDiagram.puml
  docs/images/choonwei/DeleteRecurringSessionActivityDiagram.png
  docs/images/choonwei/DeleteRecurringSessionSequenceDiagram.png
  docs/images/choonwei/ListActivityDiagram.png
  docs/images/choonwei/ListSequenceDiagram.png
  docs/images/choonwei/ListStudentActivityDiagram.png
  docs/images/choonwei/ListStudentSequenceDiagram.png
  docs/team/yungweezy.md
  src/main/java/seedu/address/logic/commands/DeleteRecurringSessionCommand.java
Labels: priority.Medium, type.Documentation

#309 DG: Minor update on email command seq. diagram
  docs/diagrams/sam/EmailCommandSequenceDiagram.puml
  docs/images/sam/EmailCommandSequenceDiagram.png
Labels: type.Documentation

#298 DG: First iteration of storage component
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/team/jonahhgohh.md
  docs/team/nowknowing.md
  docs/team/yungweezy.md
Labels: priority.Medium

#312 DG: Change formatting to UC to <h4>
  docs/DeveloperGuide.md
Labels: type.Documentation

#308 Update add std sequence diagram to include parser
  docs/diagrams/enhao/AddStudentSequenceDiagram.puml
  docs/images/enhao/AddStudentSequenceDiagram.png
Labels: type.Documentation

#311 Update UG with SS for students and fees
  docs/UserGuide.md
  docs/images/enhao/add_student - edited.png
  docs/images/enhao/add_student_result - edited.png
  docs/images/enhao/delete_student - edited.png
  docs/images/enhao/delete_student_result - edited.png
  docs/images/enhao/edit_student - edited.png
  docs/images/enhao/edit_student_result - edited.png
  docs/images/enhao/email - edited.png
  docs/images/enhao/email_client-edited.png
  docs/images/enhao/email_result - edited.png
  docs/images/enhao/fee - Edited.PNG
  docs/images/enhao/fee_result - Edited.PNG
  docs/images/enhao/find_student - edited.png
  docs/images/enhao/find_student_result - edited.png
  docs/images/enhao/sample_session.png
  docs/images/enhao/sample_student.png
Labels: type.Documentation

#307 Caution in the form of Q&A
  docs/UserGuide.md
Labels: type.Documentation

#316 Attempt to resolve bug that list number is not consecutive
  docs/UserGuide.md
Labels: type.Documentation

#306 DG for reucrring session and add recurring session feature
  docs/DeveloperGuide.md
  docs/diagrams/junwei/AddSessionSequenceDiagram.puml
  docs/diagrams/shion/AddRecurringSessionCommandParserActivityDiagram.puml
  docs/diagrams/shion/AddRecurringSessionSequenceDiagram.puml
  docs/diagrams/shion/ArchitectureSequenceDiagram.puml
  docs/diagrams/shion/DeleteSessionSequenceDiagram.puml
  docs/diagrams/shion/SessionClassDiagram.puml
  docs/images/shion/AddRecurringSessionCommandParserActivityDiagram.png
  docs/images/shion/AddRecurringSessionSequenceDiagram.png
  docs/images/shion/DeleteSessionSequenceDiagram.png
Labels: type.Documentation

#318 PPP: Minor modifications
  docs/team/samleewy.md
Labels: type.Documentation

#314 UG: Add screenshots for Sessions
  docs/UserGuide.md
  docs/images/choonwei/add_recurring_session.png
  docs/images/choonwei/add_recurring_session_result.png
  docs/images/choonwei/add_session.png
  docs/images/choonwei/add_session_result.png
  docs/images/choonwei/delete_recurring_session.png
  docs/images/choonwei/delete_recurring_session_result.png
  docs/images/choonwei/delete_session.png
  docs/images/choonwei/delete_session_recurring.png
  docs/images/choonwei/delete_session_recurring_result.png
  docs/images/choonwei/delete_session_result.png
  docs/team/yungweezy.md
Labels: priority.Medium, type.Documentation

#321 DG: Fix ordered list issue under "Managing Sessions"
  docs/UserGuide.md
  docs/team/yungweezy.md
Labels: priority.Medium, type.Documentation

#317 UG: Reminder in chronological order
  docs/UserGuide.md
  docs/images/HomePage.png
Labels: priority.Medium, type.Documentation

#322 Update add student sequence diagram
  docs/diagrams/enhao/AddStudentSequenceDiagram.puml
  docs/images/enhao/AddStudentSequenceDiagram.png
Labels: type.Documentation

#319 DG: Checking through for mistakes
  docs/DeveloperGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/junwei/AddSessionSequenceDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/junwei/AddSessionSequenceDiagram.png
Labels: type.Documentation

#323 Add page break and codify using html tags
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#320 Dg/delete session update
  docs/DeveloperGuide.md
  docs/diagrams/shion/SessionAndRecurringClassDiagram.puml
  docs/diagrams/shion/SessionClassDiagram.puml
  docs/images/shion/SessionAndRecurringClassDiagram.png
  docs/images/shion/SessionClassDiagram.png
Labels: type.Documentation

#326 ug- add dot to 4 Feature
  docs/UserGuide.md
Labels: type.Documentation

#330 UG: Add more description for URL.
  docs/UserGuide.md
Labels: priority.Low

#329 Fix: default size settings to max size
  src/main/java/seedu/address/commons/core/GuiSettings.java
Labels: type.Bug

#332 Changed UI image
  docs/UserGuide.md
  docs/images/QuickStart.png
  docs/images/Ui.png
Labels: priority.Low

#331 Add space to list activity diagram
  docs/DeveloperGuide.md
Labels: type.Documentation
